### ISSUE TITLE
Fail to compile on Microsoft Visual C++ 9.0 and 10.0

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig#8]
Building procedure:

mkdir build
cd build
cmake .. -G "NMake Makefiles"
nmake

Error message:

[ 11%] Building C object src/lib/CMakeFiles/editorconfig_shared.dir/editorconfig.obj

D:\Users\user\Documents\src\editorconfig\src\lib\editorconfig.c(267) : error C2373: 'editorconfig_is_standard_c
onformed' : redefinition; different type modifiers
        D:\Users\user\Documents\src\editorconfig\src\include\editorconfig/editorconfig.h(118) : see declaration
 of 'editorconfig_is_standard_conformed'

Weird problem. The source could be built successfully on gcc and OpenWatcom.
